// Code generated by tools/apigen. You can edit this file.

package main

import (
	"fmt"

	serviceapi "avyos.dev/api/service"
)

type Handler struct{}

func (h *Handler) StartService(sender uint32, req serviceapi.ServiceNameRequest) (serviceapi.Empty, error) {
	_ = sender
	_ = req
	var out serviceapi.Empty
	return out, fmt.Errorf("StartService not implemented")
}
func (h *Handler) StopService(sender uint32, req serviceapi.ServiceNameRequest) (serviceapi.Empty, error) {
	_ = sender
	_ = req
	var out serviceapi.Empty
	return out, fmt.Errorf("StopService not implemented")
}
func (h *Handler) RestartService(sender uint32, req serviceapi.ServiceNameRequest) (serviceapi.Empty, error) {
	_ = sender
	_ = req
	var out serviceapi.Empty
	return out, fmt.Errorf("RestartService not implemented")
}
func (h *Handler) GetStatus(sender uint32, req serviceapi.ServiceNameRequest) (serviceapi.ServiceStatus, error) {
	_ = sender
	_ = req
	var out serviceapi.ServiceStatus
	return out, fmt.Errorf("GetStatus not implemented")
}
func (h *Handler) ListServices(sender uint32, req serviceapi.Empty) (serviceapi.ServiceStatusList, error) {
	_ = sender
	_ = req
	var out serviceapi.ServiceStatusList
	return out, fmt.Errorf("ListServices not implemented")
}
func (h *Handler) SystemPoweroff(sender uint32, req serviceapi.Empty) (serviceapi.Empty, error) {
	_ = sender
	_ = req
	var out serviceapi.Empty
	return out, fmt.Errorf("SystemPoweroff not implemented")
}
func (h *Handler) SystemReboot(sender uint32, req serviceapi.Empty) (serviceapi.Empty, error) {
	_ = sender
	_ = req
	var out serviceapi.Empty
	return out, fmt.Errorf("SystemReboot not implemented")
}
