// Code generated by tools/apigen; DO NOT EDIT.

package main

import (
	"fmt"

	serviceapi "avyos.dev/api/service"
	"avyos.dev/pkg/sutra"
)

type APIHandler interface {
	StartService(sender uint32, req serviceapi.ServiceNameRequest) (serviceapi.Empty, error)
	StopService(sender uint32, req serviceapi.ServiceNameRequest) (serviceapi.Empty, error)
	RestartService(sender uint32, req serviceapi.ServiceNameRequest) (serviceapi.Empty, error)
	GetStatus(sender uint32, req serviceapi.ServiceNameRequest) (serviceapi.ServiceStatus, error)
	ListServices(sender uint32, req serviceapi.Empty) (serviceapi.ServiceStatusList, error)
	SystemPoweroff(sender uint32, req serviceapi.Empty) (serviceapi.Empty, error)
	SystemReboot(sender uint32, req serviceapi.Empty) (serviceapi.Empty, error)
}

func RegisterHandlers(service *sutra.Service, handler APIHandler) {
	service.Handle(serviceapi.RequestStartService, func(t *sutra.Transaction) ([]byte, error) {
		var req serviceapi.ServiceNameRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.StartService(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(serviceapi.RequestStopService, func(t *sutra.Transaction) ([]byte, error) {
		var req serviceapi.ServiceNameRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.StopService(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(serviceapi.RequestRestartService, func(t *sutra.Transaction) ([]byte, error) {
		var req serviceapi.ServiceNameRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.RestartService(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(serviceapi.RequestGetStatus, func(t *sutra.Transaction) ([]byte, error) {
		var req serviceapi.ServiceNameRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.GetStatus(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(serviceapi.RequestListServices, func(t *sutra.Transaction) ([]byte, error) {
		var req serviceapi.Empty
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.ListServices(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(serviceapi.RequestSystemPoweroff, func(t *sutra.Transaction) ([]byte, error) {
		var req serviceapi.Empty
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.SystemPoweroff(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(serviceapi.RequestSystemReboot, func(t *sutra.Transaction) ([]byte, error) {
		var req serviceapi.Empty
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.SystemReboot(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
