// Code generated by tools/apigen; DO NOT EDIT.

package main

import (
	"fmt"

	dbgapi "avyos.dev/api/dbg"
	"avyos.dev/pkg/sutra"
)

type APIHandler interface {
	Authenticate(sender uint32, req dbgapi.AuthRequest) (dbgapi.SessionInfo, error)
	Logout(sender uint32, req dbgapi.SessionToken) (dbgapi.Empty, error)
	RunCommand(sender uint32, req dbgapi.ExecRequest) (dbgapi.ExecResult, error)
	RunShell(sender uint32, req dbgapi.ExecRequest) (dbgapi.ExecResult, error)
	ShellOpen(sender uint32, req dbgapi.ShellOpenRequest) (dbgapi.ShellSession, error)
	ShellInput(sender uint32, req dbgapi.ShellInputRequest) error
	ShellResize(sender uint32, req dbgapi.ShellResizeRequest) error
	ShellClose(sender uint32, req dbgapi.ShellCloseRequest) error
	ReadFile(sender uint32, req dbgapi.ReadFileRequest) (dbgapi.FileChunk, error)
	WriteFile(sender uint32, req dbgapi.WriteFileRequest) (dbgapi.WriteFileResult, error)
}

func RegisterHandlers(service *sutra.Service, handler APIHandler) {
	service.Handle(dbgapi.RequestAuthenticate, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgapi.AuthRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Authenticate(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgapi.RequestLogout, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgapi.SessionToken
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Logout(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgapi.RequestRunCommand, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgapi.ExecRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.RunCommand(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgapi.RequestRunShell, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgapi.ExecRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.RunShell(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgapi.RequestShellOpen, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgapi.ShellOpenRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.ShellOpen(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgapi.RequestShellInput, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgapi.ShellInputRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		if err := handler.ShellInput(t.Sender, req); err != nil {
			return nil, err
		}
		return nil, nil
	})
	service.Handle(dbgapi.RequestShellResize, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgapi.ShellResizeRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		if err := handler.ShellResize(t.Sender, req); err != nil {
			return nil, err
		}
		return nil, nil
	})
	service.Handle(dbgapi.RequestShellClose, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgapi.ShellCloseRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		if err := handler.ShellClose(t.Sender, req); err != nil {
			return nil, err
		}
		return nil, nil
	})
	service.Handle(dbgapi.RequestReadFile, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgapi.ReadFileRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.ReadFile(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgapi.RequestWriteFile, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgapi.WriteFileRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.WriteFile(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
}

func EmitShellOutput(service *sutra.Service, destination uint32, ev dbgapi.ShellOutputEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, dbgapi.EventShellOutput, payload)
}

func EmitShellExit(service *sutra.Service, destination uint32, ev dbgapi.ShellExitEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, dbgapi.EventShellExit, payload)
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
