// Code generated by tools/apigen; DO NOT EDIT.

package dbg

import (
	"fmt"
	"time"

	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
)

const (
	ServiceName        = "dev.avyos.dbg"
	ServiceID   uint32 = 96
)

const (
	RequestAuthenticate uint16 = 0x0601
	RequestLogout       uint16 = 0x0602
	RequestRunCommand   uint16 = 0x0610
	RequestRunShell     uint16 = 0x0611
	RequestReadFile     uint16 = 0x0620
	RequestWriteFile    uint16 = 0x0621
)

type Empty struct {
}

func (v Empty) encodeTo(enc *sutra.Encoder) {
}

func (v *Empty) decodeFrom(dec *sutra.Decoder) {
}

func (v Empty) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *Empty) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type AuthRequest struct {
	Username string
	Password string
}

func (v AuthRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Username)
	enc.PutString(v.Password)
}

func (v *AuthRequest) decodeFrom(dec *sutra.Decoder) {
	v.Username = dec.String()
	v.Password = dec.String()
}

func (v AuthRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *AuthRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type SessionInfo struct {
	Token    string
	Username string
	UID      uint32
	GID      uint32
	Home     string
	Shell    string
}

func (v SessionInfo) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Token)
	enc.PutString(v.Username)
	enc.PutUint32(v.UID)
	enc.PutUint32(v.GID)
	enc.PutString(v.Home)
	enc.PutString(v.Shell)
}

func (v *SessionInfo) decodeFrom(dec *sutra.Decoder) {
	v.Token = dec.String()
	v.Username = dec.String()
	v.UID = dec.Uint32()
	v.GID = dec.Uint32()
	v.Home = dec.String()
	v.Shell = dec.String()
}

func (v SessionInfo) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *SessionInfo) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type SessionToken struct {
	Token string
}

func (v SessionToken) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Token)
}

func (v *SessionToken) decodeFrom(dec *sutra.Decoder) {
	v.Token = dec.String()
}

func (v SessionToken) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *SessionToken) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ExecRequest struct {
	Token      string
	Command    string
	Cwd        string
	TimeoutSec int32
}

func (v ExecRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Token)
	enc.PutString(v.Command)
	enc.PutString(v.Cwd)
	enc.PutInt32(v.TimeoutSec)
}

func (v *ExecRequest) decodeFrom(dec *sutra.Decoder) {
	v.Token = dec.String()
	v.Command = dec.String()
	v.Cwd = dec.String()
	v.TimeoutSec = dec.Int32()
}

func (v ExecRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ExecRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ExecResult struct {
	ExitCode        int
	Stdout          []byte
	Stderr          []byte
	StdoutTruncated bool
	StderrTruncated bool
}

func (v ExecResult) encodeTo(enc *sutra.Encoder) {
	enc.PutInt(v.ExitCode)
	enc.PutBytes(v.Stdout)
	enc.PutBytes(v.Stderr)
	enc.PutBool(v.StdoutTruncated)
	enc.PutBool(v.StderrTruncated)
}

func (v *ExecResult) decodeFrom(dec *sutra.Decoder) {
	v.ExitCode = dec.Int()
	v.Stdout = dec.Bytes()
	v.Stderr = dec.Bytes()
	v.StdoutTruncated = dec.Bool()
	v.StderrTruncated = dec.Bool()
}

func (v ExecResult) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ExecResult) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ReadFileRequest struct {
	Token  string
	Path   string
	Offset uint64
	Size   uint32
}

func (v ReadFileRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Token)
	enc.PutString(v.Path)
	enc.PutUint64(v.Offset)
	enc.PutUint32(v.Size)
}

func (v *ReadFileRequest) decodeFrom(dec *sutra.Decoder) {
	v.Token = dec.String()
	v.Path = dec.String()
	v.Offset = dec.Uint64()
	v.Size = dec.Uint32()
}

func (v ReadFileRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ReadFileRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type FileChunk struct {
	Data []byte
	Eof  bool
}

func (v FileChunk) encodeTo(enc *sutra.Encoder) {
	enc.PutBytes(v.Data)
	enc.PutBool(v.Eof)
}

func (v *FileChunk) decodeFrom(dec *sutra.Decoder) {
	v.Data = dec.Bytes()
	v.Eof = dec.Bool()
}

func (v FileChunk) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *FileChunk) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type WriteFileRequest struct {
	Token    string
	Path     string
	Offset   uint64
	Data     []byte
	Truncate bool
	Mode     uint32
}

func (v WriteFileRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Token)
	enc.PutString(v.Path)
	enc.PutUint64(v.Offset)
	enc.PutBytes(v.Data)
	enc.PutBool(v.Truncate)
	enc.PutUint32(v.Mode)
}

func (v *WriteFileRequest) decodeFrom(dec *sutra.Decoder) {
	v.Token = dec.String()
	v.Path = dec.String()
	v.Offset = dec.Uint64()
	v.Data = dec.Bytes()
	v.Truncate = dec.Bool()
	v.Mode = dec.Uint32()
}

func (v WriteFileRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *WriteFileRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type WriteFileResult struct {
	Written uint32
}

func (v WriteFileResult) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.Written)
}

func (v *WriteFileResult) decodeFrom(dec *sutra.Decoder) {
	v.Written = dec.Uint32()
}

func (v WriteFileResult) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *WriteFileResult) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type Client struct {
	client  *sutra.Client
	timeout time.Duration
}

func NewClient(socketPath string) (*Client, error) {
	if socketPath == "" {
		socketPath = fs.Resolve("system:%s", ServiceName)
	}
	c, err := sutra.Connect(socketPath)
	if err != nil {
		return nil, err
	}
	return &Client{
		client:  c,
		timeout: 5 * time.Second,
	}, nil
}

func (c *Client) Close() error {
	return c.client.Close()
}

func (c *Client) SetTimeout(timeout time.Duration) {
	c.timeout = timeout
}

func (c *Client) Authenticate(req AuthRequest) (SessionInfo, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero SessionInfo
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestAuthenticate, payload, c.timeout)
	if err != nil {
		var zero SessionInfo
		return zero, err
	}
	var out SessionInfo
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero SessionInfo
		return zero, err
	}
	return out, nil
}

func (c *Client) Logout(req SessionToken) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestLogout, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) RunCommand(req ExecRequest) (ExecResult, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero ExecResult
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestRunCommand, payload, c.timeout)
	if err != nil {
		var zero ExecResult
		return zero, err
	}
	var out ExecResult
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero ExecResult
		return zero, err
	}
	return out, nil
}

func (c *Client) RunShell(req ExecRequest) (ExecResult, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero ExecResult
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestRunShell, payload, c.timeout)
	if err != nil {
		var zero ExecResult
		return zero, err
	}
	var out ExecResult
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero ExecResult
		return zero, err
	}
	return out, nil
}

func (c *Client) ReadFile(req ReadFileRequest) (FileChunk, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero FileChunk
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestReadFile, payload, c.timeout)
	if err != nil {
		var zero FileChunk
		return zero, err
	}
	var out FileChunk
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero FileChunk
		return zero, err
	}
	return out, nil
}

func (c *Client) WriteFile(req WriteFileRequest) (WriteFileResult, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero WriteFileResult
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestWriteFile, payload, c.timeout)
	if err != nil {
		var zero WriteFileResult
		return zero, err
	}
	var out WriteFileResult
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero WriteFileResult
		return zero, err
	}
	return out, nil
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
