// Code generated by tools/apigen; DO NOT EDIT.

package displayapi

import (
	"fmt"
	"time"

	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/graphics"
	"avyos.dev/pkg/sutra"
)

const (
	ServiceName        = "display"
	ServiceID   uint32 = 16
)

const (
	RequestCreateWindow       uint16 = 0x0201
	RequestDestroyWindow      uint16 = 0x0202
	RequestSetTitle           uint16 = 0x0203
	RequestDamage             uint16 = 0x0204
	RequestResize             uint16 = 0x0205
	RequestMove               uint16 = 0x0206
	RequestCreateLayer        uint16 = 0x0207
	RequestCreatePopup        uint16 = 0x0208
	RequestListWindows        uint16 = 0x0209
	RequestSetWindowState     uint16 = 0x020a
	RequestRegisterSession    uint16 = 0x020b
	RequestSetActiveSession   uint16 = 0x020c
	RequestGetActiveSession   uint16 = 0x020d
	RequestRegisterShortcut   uint16 = 0x020e
	RequestUnregisterShortcut uint16 = 0x020f
)

const (
	EventWindowCreated    uint16 = 0x0301
	EventConfigure        uint16 = 0x0302
	EventClose            uint16 = 0x0303
	EventPointerEnter     uint16 = 0x0304
	EventPointerLeave     uint16 = 0x0305
	EventPointerMotion    uint16 = 0x0306
	EventPointerButton    uint16 = 0x0307
	EventKey              uint16 = 0x0308
	EventFocus            uint16 = 0x0309
	EventMoved            uint16 = 0x030a
	EventWindowList       uint16 = 0x030b
	EventSessionActivated uint16 = 0x030c
	EventSessionSuspended uint16 = 0x030d
	EventSessionResumed   uint16 = 0x030e
	EventShortcut         uint16 = 0x030f
)

type Empty struct {
}

func (v Empty) encodeTo(enc *sutra.Encoder) {
}

func (v *Empty) decodeFrom(dec *sutra.Decoder) {
}

func (v Empty) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *Empty) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type CreateWindowRequest struct {
	ShmKey string
	Width  int
	Height int
	Stride int
}

func (v CreateWindowRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.ShmKey)
	enc.PutInt(v.Width)
	enc.PutInt(v.Height)
	enc.PutInt(v.Stride)
}

func (v *CreateWindowRequest) decodeFrom(dec *sutra.Decoder) {
	v.ShmKey = dec.String()
	v.Width = dec.Int()
	v.Height = dec.Int()
	v.Stride = dec.Int()
}

func (v CreateWindowRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *CreateWindowRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type CreateLayerRequest struct {
	Layer      uint32
	Anchor     uint32
	Exclusive  int
	OpaqueHint bool
	ShmKey     string
	Width      int
	Height     int
	Stride     int
}

func (v CreateLayerRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.Layer)
	enc.PutUint32(v.Anchor)
	enc.PutInt(v.Exclusive)
	enc.PutBool(v.OpaqueHint)
	enc.PutString(v.ShmKey)
	enc.PutInt(v.Width)
	enc.PutInt(v.Height)
	enc.PutInt(v.Stride)
}

func (v *CreateLayerRequest) decodeFrom(dec *sutra.Decoder) {
	v.Layer = dec.Uint32()
	v.Anchor = dec.Uint32()
	v.Exclusive = dec.Int()
	v.OpaqueHint = dec.Bool()
	v.ShmKey = dec.String()
	v.Width = dec.Int()
	v.Height = dec.Int()
	v.Stride = dec.Int()
}

func (v CreateLayerRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *CreateLayerRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type CreatePopupRequest struct {
	ParentID uint32
	X        int
	Y        int
	ShmKey   string
	Width    int
	Height   int
	Stride   int
}

func (v CreatePopupRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.ParentID)
	enc.PutInt(v.X)
	enc.PutInt(v.Y)
	enc.PutString(v.ShmKey)
	enc.PutInt(v.Width)
	enc.PutInt(v.Height)
	enc.PutInt(v.Stride)
}

func (v *CreatePopupRequest) decodeFrom(dec *sutra.Decoder) {
	v.ParentID = dec.Uint32()
	v.X = dec.Int()
	v.Y = dec.Int()
	v.ShmKey = dec.String()
	v.Width = dec.Int()
	v.Height = dec.Int()
	v.Stride = dec.Int()
}

func (v CreatePopupRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *CreatePopupRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type DestroyWindowRequest struct {
	WindowID uint32
}

func (v DestroyWindowRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
}

func (v *DestroyWindowRequest) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
}

func (v DestroyWindowRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *DestroyWindowRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type SetTitleRequest struct {
	WindowID uint32
	Title    string
}

func (v SetTitleRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutString(v.Title)
}

func (v *SetTitleRequest) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.Title = dec.String()
}

func (v SetTitleRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *SetTitleRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type DamageRequest struct {
	WindowID uint32
	X        int
	Y        int
	Width    int
	Height   int
}

func (v DamageRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutInt(v.X)
	enc.PutInt(v.Y)
	enc.PutInt(v.Width)
	enc.PutInt(v.Height)
}

func (v *DamageRequest) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.X = dec.Int()
	v.Y = dec.Int()
	v.Width = dec.Int()
	v.Height = dec.Int()
}

func (v DamageRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *DamageRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ResizeRequest struct {
	WindowID uint32
	ShmKey   string
	Width    int
	Height   int
	Stride   int
}

func (v ResizeRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutString(v.ShmKey)
	enc.PutInt(v.Width)
	enc.PutInt(v.Height)
	enc.PutInt(v.Stride)
}

func (v *ResizeRequest) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.ShmKey = dec.String()
	v.Width = dec.Int()
	v.Height = dec.Int()
	v.Stride = dec.Int()
}

func (v ResizeRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ResizeRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type MoveRequest struct {
	WindowID uint32
	X        int
	Y        int
}

func (v MoveRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutInt(v.X)
	enc.PutInt(v.Y)
}

func (v *MoveRequest) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.X = dec.Int()
	v.Y = dec.Int()
}

func (v MoveRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *MoveRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type SetWindowStateRequest struct {
	WindowID uint32
	Action   uint32
}

func (v SetWindowStateRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutUint32(v.Action)
}

func (v *SetWindowStateRequest) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.Action = dec.Uint32()
}

func (v SetWindowStateRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *SetWindowStateRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type WindowCreatedEvent struct {
	WindowID uint32
	X        int
	Y        int
}

func (v WindowCreatedEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutInt(v.X)
	enc.PutInt(v.Y)
}

func (v *WindowCreatedEvent) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.X = dec.Int()
	v.Y = dec.Int()
}

func (v WindowCreatedEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *WindowCreatedEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ConfigureEvent struct {
	WindowID uint32
	Width    int
	Height   int
}

func (v ConfigureEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutInt(v.Width)
	enc.PutInt(v.Height)
}

func (v *ConfigureEvent) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.Width = dec.Int()
	v.Height = dec.Int()
}

func (v ConfigureEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ConfigureEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type CloseEvent struct {
	WindowID uint32
}

func (v CloseEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
}

func (v *CloseEvent) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
}

func (v CloseEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *CloseEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type PointerEnterEvent struct {
	WindowID uint32
	X        int
	Y        int
}

func (v PointerEnterEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutInt(v.X)
	enc.PutInt(v.Y)
}

func (v *PointerEnterEvent) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.X = dec.Int()
	v.Y = dec.Int()
}

func (v PointerEnterEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *PointerEnterEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type PointerLeaveEvent struct {
	WindowID uint32
}

func (v PointerLeaveEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
}

func (v *PointerLeaveEvent) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
}

func (v PointerLeaveEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *PointerLeaveEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type PointerMotionEvent struct {
	WindowID uint32
	X        int
	Y        int
}

func (v PointerMotionEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutInt(v.X)
	enc.PutInt(v.Y)
}

func (v *PointerMotionEvent) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.X = dec.Int()
	v.Y = dec.Int()
}

func (v PointerMotionEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *PointerMotionEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type PointerButtonEvent struct {
	WindowID uint32
	Button   int
	Pressed  bool
}

func (v PointerButtonEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutInt(v.Button)
	enc.PutBool(v.Pressed)
}

func (v *PointerButtonEvent) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.Button = dec.Int()
	v.Pressed = dec.Bool()
}

func (v PointerButtonEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *PointerButtonEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type KeyEvent struct {
	WindowID uint32
	Key      graphics.Key
	Char     rune
	Pressed  bool
}

func (v KeyEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutInt(int(v.Key))
	enc.PutRune(v.Char)
	enc.PutBool(v.Pressed)
}

func (v *KeyEvent) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.Key = graphics.Key(dec.Int())
	v.Char = dec.Rune()
	v.Pressed = dec.Bool()
}

func (v KeyEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *KeyEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type FocusEvent struct {
	WindowID uint32
	Focused  bool
}

func (v FocusEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutBool(v.Focused)
}

func (v *FocusEvent) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.Focused = dec.Bool()
}

func (v FocusEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *FocusEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type MovedEvent struct {
	WindowID uint32
	X        int
	Y        int
}

func (v MovedEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.WindowID)
	enc.PutInt(v.X)
	enc.PutInt(v.Y)
}

func (v *MovedEvent) decodeFrom(dec *sutra.Decoder) {
	v.WindowID = dec.Uint32()
	v.X = dec.Int()
	v.Y = dec.Int()
}

func (v MovedEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *MovedEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type WindowListItem struct {
	ID    uint32
	Flags uint32
	Title string
}

func (v WindowListItem) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.ID)
	enc.PutUint32(v.Flags)
	enc.PutString(v.Title)
}

func (v *WindowListItem) decodeFrom(dec *sutra.Decoder) {
	v.ID = dec.Uint32()
	v.Flags = dec.Uint32()
	v.Title = dec.String()
}

func (v WindowListItem) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *WindowListItem) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type WindowListEvent struct {
	Windows []WindowListItem
}

func (v WindowListEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(uint32(len(v.Windows)))
	for i := range v.Windows {
		v.Windows[i].encodeTo(enc)
	}
}

func (v *WindowListEvent) decodeFrom(dec *sutra.Decoder) {
	{
		n := int(dec.Uint32())
		v.Windows = make([]WindowListItem, n)
		for i := range v.Windows {
			v.Windows[i].decodeFrom(dec)
		}
	}
}

func (v WindowListEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *WindowListEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type RegisterSessionRequest struct {
	SessionID uint32
	UID       uint32
}

func (v RegisterSessionRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.SessionID)
	enc.PutUint32(v.UID)
}

func (v *RegisterSessionRequest) decodeFrom(dec *sutra.Decoder) {
	v.SessionID = dec.Uint32()
	v.UID = dec.Uint32()
}

func (v RegisterSessionRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *RegisterSessionRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type SetActiveSessionRequest struct {
	SessionID uint32
}

func (v SetActiveSessionRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.SessionID)
}

func (v *SetActiveSessionRequest) decodeFrom(dec *sutra.Decoder) {
	v.SessionID = dec.Uint32()
}

func (v SetActiveSessionRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *SetActiveSessionRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ActiveSessionEvent struct {
	SessionID uint32
}

func (v ActiveSessionEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.SessionID)
}

func (v *ActiveSessionEvent) decodeFrom(dec *sutra.Decoder) {
	v.SessionID = dec.Uint32()
}

func (v ActiveSessionEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ActiveSessionEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type RegisterShortcutRequest struct {
	ShortcutID uint32
	WindowID   uint32
	Scope      uint32
	Key        graphics.Key
	Modifiers  uint8
}

func (v RegisterShortcutRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.ShortcutID)
	enc.PutUint32(v.WindowID)
	enc.PutUint32(v.Scope)
	enc.PutInt(int(v.Key))
	enc.PutUint8(v.Modifiers)
}

func (v *RegisterShortcutRequest) decodeFrom(dec *sutra.Decoder) {
	v.ShortcutID = dec.Uint32()
	v.WindowID = dec.Uint32()
	v.Scope = dec.Uint32()
	v.Key = graphics.Key(dec.Int())
	v.Modifiers = dec.Uint8()
}

func (v RegisterShortcutRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *RegisterShortcutRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type UnregisterShortcutRequest struct {
	ShortcutID uint32
}

func (v UnregisterShortcutRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.ShortcutID)
}

func (v *UnregisterShortcutRequest) decodeFrom(dec *sutra.Decoder) {
	v.ShortcutID = dec.Uint32()
}

func (v UnregisterShortcutRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *UnregisterShortcutRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ShortcutEvent struct {
	ShortcutID uint32
	WindowID   uint32
	Scope      uint32
	Key        graphics.Key
	Modifiers  uint8
}

func (v ShortcutEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.ShortcutID)
	enc.PutUint32(v.WindowID)
	enc.PutUint32(v.Scope)
	enc.PutInt(int(v.Key))
	enc.PutUint8(v.Modifiers)
}

func (v *ShortcutEvent) decodeFrom(dec *sutra.Decoder) {
	v.ShortcutID = dec.Uint32()
	v.WindowID = dec.Uint32()
	v.Scope = dec.Uint32()
	v.Key = graphics.Key(dec.Int())
	v.Modifiers = dec.Uint8()
}

func (v ShortcutEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ShortcutEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type Client struct {
	client  *sutra.Client
	timeout time.Duration
}

func NewClient(socketPath string) (*Client, error) {
	if socketPath == "" {
		socketPath = fs.Resolve("service:" + ServiceName)
	}
	c, err := sutra.Connect(socketPath)
	if err != nil {
		return nil, err
	}
	return &Client{
		client:  c,
		timeout: 5 * time.Second,
	}, nil
}

func (c *Client) Close() error {
	return c.client.Close()
}

func (c *Client) SetTimeout(timeout time.Duration) {
	c.timeout = timeout
}

func (c *Client) CreateWindow(req CreateWindowRequest) (WindowCreatedEvent, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero WindowCreatedEvent
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestCreateWindow, payload, c.timeout)
	if err != nil {
		var zero WindowCreatedEvent
		return zero, err
	}
	var out WindowCreatedEvent
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero WindowCreatedEvent
		return zero, err
	}
	return out, nil
}

func (c *Client) DestroyWindow(req DestroyWindowRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestDestroyWindow, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) SetTitle(req SetTitleRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestSetTitle, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) Damage(req DamageRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestDamage, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) Resize(req ResizeRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestResize, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) Move(req MoveRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestMove, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) CreateLayer(req CreateLayerRequest) (WindowCreatedEvent, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero WindowCreatedEvent
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestCreateLayer, payload, c.timeout)
	if err != nil {
		var zero WindowCreatedEvent
		return zero, err
	}
	var out WindowCreatedEvent
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero WindowCreatedEvent
		return zero, err
	}
	return out, nil
}

func (c *Client) CreatePopup(req CreatePopupRequest) (WindowCreatedEvent, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero WindowCreatedEvent
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestCreatePopup, payload, c.timeout)
	if err != nil {
		var zero WindowCreatedEvent
		return zero, err
	}
	var out WindowCreatedEvent
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero WindowCreatedEvent
		return zero, err
	}
	return out, nil
}

func (c *Client) ListWindows(req Empty) (WindowListEvent, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero WindowListEvent
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestListWindows, payload, c.timeout)
	if err != nil {
		var zero WindowListEvent
		return zero, err
	}
	var out WindowListEvent
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero WindowListEvent
		return zero, err
	}
	return out, nil
}

func (c *Client) SetWindowState(req SetWindowStateRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestSetWindowState, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) RegisterSession(req RegisterSessionRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestRegisterSession, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) SetActiveSession(req SetActiveSessionRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestSetActiveSession, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) GetActiveSession(req Empty) (ActiveSessionEvent, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero ActiveSessionEvent
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestGetActiveSession, payload, c.timeout)
	if err != nil {
		var zero ActiveSessionEvent
		return zero, err
	}
	var out ActiveSessionEvent
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero ActiveSessionEvent
		return zero, err
	}
	return out, nil
}

func (c *Client) RegisterShortcut(req RegisterShortcutRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestRegisterShortcut, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) UnregisterShortcut(req UnregisterShortcutRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestUnregisterShortcut, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) OnWindowCreated(fn func(sender uint32, ev WindowCreatedEvent)) {
	c.client.On(EventWindowCreated, func(t *sutra.Transaction) {
		var value WindowCreatedEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnConfigure(fn func(sender uint32, ev ConfigureEvent)) {
	c.client.On(EventConfigure, func(t *sutra.Transaction) {
		var value ConfigureEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnClose(fn func(sender uint32, ev CloseEvent)) {
	c.client.On(EventClose, func(t *sutra.Transaction) {
		var value CloseEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnPointerEnter(fn func(sender uint32, ev PointerEnterEvent)) {
	c.client.On(EventPointerEnter, func(t *sutra.Transaction) {
		var value PointerEnterEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnPointerLeave(fn func(sender uint32, ev PointerLeaveEvent)) {
	c.client.On(EventPointerLeave, func(t *sutra.Transaction) {
		var value PointerLeaveEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnPointerMotion(fn func(sender uint32, ev PointerMotionEvent)) {
	c.client.On(EventPointerMotion, func(t *sutra.Transaction) {
		var value PointerMotionEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnPointerButton(fn func(sender uint32, ev PointerButtonEvent)) {
	c.client.On(EventPointerButton, func(t *sutra.Transaction) {
		var value PointerButtonEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnKey(fn func(sender uint32, ev KeyEvent)) {
	c.client.On(EventKey, func(t *sutra.Transaction) {
		var value KeyEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnFocus(fn func(sender uint32, ev FocusEvent)) {
	c.client.On(EventFocus, func(t *sutra.Transaction) {
		var value FocusEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnMoved(fn func(sender uint32, ev MovedEvent)) {
	c.client.On(EventMoved, func(t *sutra.Transaction) {
		var value MovedEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnWindowList(fn func(sender uint32, ev WindowListEvent)) {
	c.client.On(EventWindowList, func(t *sutra.Transaction) {
		var value WindowListEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnSessionActivated(fn func(sender uint32, ev ActiveSessionEvent)) {
	c.client.On(EventSessionActivated, func(t *sutra.Transaction) {
		var value ActiveSessionEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnSessionSuspended(fn func(sender uint32, ev ActiveSessionEvent)) {
	c.client.On(EventSessionSuspended, func(t *sutra.Transaction) {
		var value ActiveSessionEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnSessionResumed(fn func(sender uint32, ev ActiveSessionEvent)) {
	c.client.On(EventSessionResumed, func(t *sutra.Transaction) {
		var value ActiveSessionEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnShortcut(fn func(sender uint32, ev ShortcutEvent)) {
	c.client.On(EventShortcut, func(t *sutra.Transaction) {
		var value ShortcutEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
