// Code generated by tools/apigen. You can edit this file.

package main

import (
	"fmt"

	settingsapi "avyos.dev/api/settings"
)

type Handler struct{}

func (h *Handler) RawGet(sender uint32, req settingsapi.KeyRequest) (settingsapi.GetResponse, error) {
	_ = sender
	_ = req
	var out settingsapi.GetResponse
	return out, fmt.Errorf("RawGet not implemented")
}
func (h *Handler) RawSet(sender uint32, req settingsapi.SetRequest) (settingsapi.Empty, error) {
	_ = sender
	_ = req
	var out settingsapi.Empty
	return out, fmt.Errorf("RawSet not implemented")
}
func (h *Handler) RawList(sender uint32, req settingsapi.ListRequest) (settingsapi.EntryList, error) {
	_ = sender
	_ = req
	var out settingsapi.EntryList
	return out, fmt.Errorf("RawList not implemented")
}
