// Code generated by tools/apigen; DO NOT EDIT.

package main

import (
	"fmt"

	settingsapi "avyos.dev/api/settings"
	"avyos.dev/pkg/sutra"
)

type APIHandler interface {
	RawGet(sender uint32, req settingsapi.KeyRequest) (settingsapi.GetResponse, error)
	RawSet(sender uint32, req settingsapi.SetRequest) (settingsapi.Empty, error)
	RawList(sender uint32, req settingsapi.ListRequest) (settingsapi.EntryList, error)
}

func RegisterHandlers(service *sutra.Service, handler APIHandler) {
	service.Handle(settingsapi.RequestRawGet, func(t *sutra.Transaction) ([]byte, error) {
		var req settingsapi.KeyRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.RawGet(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(settingsapi.RequestRawSet, func(t *sutra.Transaction) ([]byte, error) {
		var req settingsapi.SetRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.RawSet(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(settingsapi.RequestRawList, func(t *sutra.Transaction) ([]byte, error) {
		var req settingsapi.ListRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.RawList(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
}

func EmitSettingsChanged(service *sutra.Service, destination uint32, ev settingsapi.ChangedEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, settingsapi.EventSettingsChanged, payload)
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
