// Code generated by tools/apigen; DO NOT EDIT.

package main

import (
	"fmt"

	dbgdapi "avyos.dev/api/dbgd"
	"avyos.dev/pkg/sutra"
)

type APIHandler interface {
	Authenticate(sender uint32, req dbgdapi.AuthRequest) (dbgdapi.SessionInfo, error)
	Logout(sender uint32, req dbgdapi.SessionToken) (dbgdapi.Empty, error)
	RunCommand(sender uint32, req dbgdapi.ExecRequest) (dbgdapi.ExecResult, error)
	RunShell(sender uint32, req dbgdapi.ExecRequest) (dbgdapi.ExecResult, error)
	ReadFile(sender uint32, req dbgdapi.ReadFileRequest) (dbgdapi.FileChunk, error)
	WriteFile(sender uint32, req dbgdapi.WriteFileRequest) (dbgdapi.WriteFileResult, error)
}

func RegisterHandlers(service *sutra.Service, handler APIHandler) {
	service.Handle(dbgdapi.RequestAuthenticate, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgdapi.AuthRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Authenticate(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgdapi.RequestLogout, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgdapi.SessionToken
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Logout(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgdapi.RequestRunCommand, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgdapi.ExecRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.RunCommand(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgdapi.RequestRunShell, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgdapi.ExecRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.RunShell(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgdapi.RequestReadFile, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgdapi.ReadFileRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.ReadFile(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(dbgdapi.RequestWriteFile, func(t *sutra.Transaction) ([]byte, error) {
		var req dbgdapi.WriteFileRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.WriteFile(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
