// Code generated by tools/apigen; DO NOT EDIT.

package serviceapi

import (
	"fmt"
	"time"

	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
)

const (
	ServiceName        = "service-manager"
	ServiceID   uint32 = 80
)

const (
	RequestStartService   uint16 = 0x0110
	RequestStopService    uint16 = 0x0111
	RequestRestartService uint16 = 0x0112
	RequestGetStatus      uint16 = 0x0113
	RequestListServices   uint16 = 0x0114
	RequestSystemPoweroff uint16 = 0x0115
	RequestSystemReboot   uint16 = 0x0116
)

type Empty struct {
}

func (v Empty) encodeTo(enc *sutra.Encoder) {
}

func (v *Empty) decodeFrom(dec *sutra.Decoder) {
}

func (v Empty) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *Empty) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ServiceNameRequest struct {
	Name string
}

func (v ServiceNameRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Name)
}

func (v *ServiceNameRequest) decodeFrom(dec *sutra.Decoder) {
	v.Name = dec.String()
}

func (v ServiceNameRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ServiceNameRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ServiceStatus struct {
	Name        string
	Description string
	Type        string
	Restart     string
	Running     bool
	Started     bool
	Failed      bool
	PID         int
}

func (v ServiceStatus) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Name)
	enc.PutString(v.Description)
	enc.PutString(v.Type)
	enc.PutString(v.Restart)
	enc.PutBool(v.Running)
	enc.PutBool(v.Started)
	enc.PutBool(v.Failed)
	enc.PutInt(v.PID)
}

func (v *ServiceStatus) decodeFrom(dec *sutra.Decoder) {
	v.Name = dec.String()
	v.Description = dec.String()
	v.Type = dec.String()
	v.Restart = dec.String()
	v.Running = dec.Bool()
	v.Started = dec.Bool()
	v.Failed = dec.Bool()
	v.PID = dec.Int()
}

func (v ServiceStatus) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ServiceStatus) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ServiceStatusList struct {
	Items []ServiceStatus
}

func (v ServiceStatusList) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(uint32(len(v.Items)))
	for i := range v.Items {
		v.Items[i].encodeTo(enc)
	}
}

func (v *ServiceStatusList) decodeFrom(dec *sutra.Decoder) {
	{
		n := int(dec.Uint32())
		v.Items = make([]ServiceStatus, n)
		for i := range v.Items {
			v.Items[i].decodeFrom(dec)
		}
	}
}

func (v ServiceStatusList) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ServiceStatusList) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type Client struct {
	client  *sutra.Client
	timeout time.Duration
}

func NewClient(socketPath string) (*Client, error) {
	if socketPath == "" {
		socketPath = fs.Resolve("service:" + ServiceName)
	}
	c, err := sutra.Connect(socketPath)
	if err != nil {
		return nil, err
	}
	return &Client{
		client:  c,
		timeout: 5 * time.Second,
	}, nil
}

func (c *Client) Close() error {
	return c.client.Close()
}

func (c *Client) SetTimeout(timeout time.Duration) {
	c.timeout = timeout
}

func (c *Client) StartService(req ServiceNameRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestStartService, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) StopService(req ServiceNameRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestStopService, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) RestartService(req ServiceNameRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestRestartService, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) GetStatus(req ServiceNameRequest) (ServiceStatus, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero ServiceStatus
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestGetStatus, payload, c.timeout)
	if err != nil {
		var zero ServiceStatus
		return zero, err
	}
	var out ServiceStatus
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero ServiceStatus
		return zero, err
	}
	return out, nil
}

func (c *Client) ListServices(req Empty) (ServiceStatusList, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero ServiceStatusList
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestListServices, payload, c.timeout)
	if err != nil {
		var zero ServiceStatusList
		return zero, err
	}
	var out ServiceStatusList
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero ServiceStatusList
		return zero, err
	}
	return out, nil
}

func (c *Client) SystemPoweroff(req Empty) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestSystemPoweroff, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) SystemReboot(req Empty) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestSystemReboot, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
