// Code generated by tools/apigen; DO NOT EDIT.

package settings

import (
	"fmt"
	"time"

	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
)

const (
	ServiceName        = "dev.avyos.settings"
	ServiceID   uint32 = 96
)

const (
	RequestRawGet  uint16 = 0x0201
	RequestRawSet  uint16 = 0x0202
	RequestRawList uint16 = 0x0203
)

const (
	EventSettingsChanged uint16 = 0x0301
)

type Empty struct {
}

func (v Empty) encodeTo(enc *sutra.Encoder) {
}

func (v *Empty) decodeFrom(dec *sutra.Decoder) {
}

func (v Empty) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *Empty) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type KeyRequest struct {
	Key string
}

func (v KeyRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Key)
}

func (v *KeyRequest) decodeFrom(dec *sutra.Decoder) {
	v.Key = dec.String()
}

func (v KeyRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *KeyRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type SetRequest struct {
	Key   string
	Value string
}

func (v SetRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Key)
	enc.PutString(v.Value)
}

func (v *SetRequest) decodeFrom(dec *sutra.Decoder) {
	v.Key = dec.String()
	v.Value = dec.String()
}

func (v SetRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *SetRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ListRequest struct {
	Prefix string
}

func (v ListRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Prefix)
}

func (v *ListRequest) decodeFrom(dec *sutra.Decoder) {
	v.Prefix = dec.String()
}

func (v ListRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ListRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type GetResponse struct {
	Value string
}

func (v GetResponse) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Value)
}

func (v *GetResponse) decodeFrom(dec *sutra.Decoder) {
	v.Value = dec.String()
}

func (v GetResponse) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *GetResponse) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type Entry struct {
	Key   string
	Value string
}

func (v Entry) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Key)
	enc.PutString(v.Value)
}

func (v *Entry) decodeFrom(dec *sutra.Decoder) {
	v.Key = dec.String()
	v.Value = dec.String()
}

func (v Entry) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *Entry) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type EntryList struct {
	Items []Entry
}

func (v EntryList) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(uint32(len(v.Items)))
	for i := range v.Items {
		v.Items[i].encodeTo(enc)
	}
}

func (v *EntryList) decodeFrom(dec *sutra.Decoder) {
	{
		n := int(dec.Uint32())
		v.Items = make([]Entry, n)
		for i := range v.Items {
			v.Items[i].decodeFrom(dec)
		}
	}
}

func (v EntryList) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *EntryList) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ChangedEvent struct {
	Key   string
	Value string
}

func (v ChangedEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Key)
	enc.PutString(v.Value)
}

func (v *ChangedEvent) decodeFrom(dec *sutra.Decoder) {
	v.Key = dec.String()
	v.Value = dec.String()
}

func (v ChangedEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ChangedEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type Client struct {
	client  *sutra.Client
	timeout time.Duration
}

func NewClient(socketPath string) (*Client, error) {
	if socketPath == "" {
		socketPath = fs.Resolve("service:" + ServiceName)
	}
	c, err := sutra.Connect(socketPath)
	if err != nil {
		return nil, err
	}
	return &Client{
		client:  c,
		timeout: 5 * time.Second,
	}, nil
}

func (c *Client) Close() error {
	return c.client.Close()
}

func (c *Client) SetTimeout(timeout time.Duration) {
	c.timeout = timeout
}

func (c *Client) RawGet(req KeyRequest) (GetResponse, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero GetResponse
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestRawGet, payload, c.timeout)
	if err != nil {
		var zero GetResponse
		return zero, err
	}
	var out GetResponse
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero GetResponse
		return zero, err
	}
	return out, nil
}

func (c *Client) RawSet(req SetRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestRawSet, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) RawList(req ListRequest) (EntryList, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero EntryList
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestRawList, payload, c.timeout)
	if err != nil {
		var zero EntryList
		return zero, err
	}
	var out EntryList
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero EntryList
		return zero, err
	}
	return out, nil
}

func (c *Client) OnSettingsChanged(fn func(sender uint32, ev ChangedEvent)) {
	c.client.On(EventSettingsChanged, func(t *sutra.Transaction) {
		var value ChangedEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
