shell = /avyos/cmd/shell
hostname = avyos
services = uevent display login distro

[rescue]
enable = true
# tty = /dev/ttyS0

[environment]
PATH = /avyos/cmd

[network]
devices = lo eth0

[network.eth0]
ip = 10.0.2.15/24
route = 10.0.2.2
