/*
 * Copyright (c) 2026 Manjeet Singh <itsmanjeet1998@gmail.com>.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

type uint16Value uint16
type uint32Value uint32

func (v *uint16Value) UnmarshalJSON(data []byte) error {
	n, err := parseFlexibleUint(data, 16)
	if err != nil {
		return err
	}
	*v = uint16Value(n)
	return nil
}

func (v *uint32Value) UnmarshalJSON(data []byte) error {
	n, err := parseFlexibleUint(data, 32)
	if err != nil {
		return err
	}
	*v = uint32Value(n)
	return nil
}

func parseFlexibleUint(data []byte, bits int) (uint64, error) {
	data = bytes.TrimSpace(data)
	if len(data) == 0 {
		return 0, errors.New("empty numeric value")
	}
	if data[0] == '"' {
		var s string
		if err := json.Unmarshal(data, &s); err != nil {
			return 0, err
		}
		s = strings.TrimSpace(s)
		if s == "" {
			return 0, errors.New("empty numeric string")
		}
		return strconv.ParseUint(s, 0, bits)
	}
	return strconv.ParseUint(string(data), 10, bits)
}

type apiSpec struct {
	Service  serviceSpec  `json:"service"`
	Imports  []string     `json:"imports,omitempty"`
	Types    []typeSpec   `json:"types,omitempty"`
	Requests []methodSpec `json:"requests,omitempty"` // client -> server
	Events   []methodSpec `json:"events,omitempty"`   // server -> client
}

type serviceSpec struct {
	Name    string      `json:"name"`
	ID      uint32Value `json:"id"`
	Package string      `json:"package,omitempty"` // defaults to api/<name> dir name
}

type typeSpec struct {
	Name   string      `json:"name"`
	Fields []fieldSpec `json:"fields,omitempty"`
}

type methodSpec struct {
	Name         string      `json:"name"`
	ID           uint16Value `json:"id"`
	RequestType  string      `json:"request_type,omitempty"`
	ResponseType string      `json:"response_type,omitempty"`
	PayloadType  string      `json:"payload_type,omitempty"` // alias for request_type
	OneWay       bool        `json:"one_way,omitempty"`
	Comment      string      `json:"comment,omitempty"`
}

type fieldSpec struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type methodInfo struct {
	Name               string
	RequestID          uint16
	RequestConst       string
	EventConst         string
	RequestType        string
	ResponseType       string
	ServerRequestType  string
	ServerResponseType string
	OneWay             bool
	Comment            string
}

type typeInfo struct {
	Name   string
	Fields []fieldInfo
}

type fieldInfo struct {
	Name      string
	Type      string
	EncMethod string // encoder method, e.g. "PutUint32"
	DecMethod string // decoder method, e.g. "Uint32"
	EncCast   string // cast wrapper for encoding, e.g. "int" → enc.PutInt(int(v.X))
	DecCast   string // cast wrapper for decoding, e.g. "graphics.Key" → v.Key = graphics.Key(dec.Int())
	IsSlice   bool   // true for []T fields
	SliceElem string // element type if IsSlice (e.g. "WindowListItem")
}

type templateData struct {
	Generator       string
	ServiceDir      string
	ServiceName     string
	ServiceID       uint32
	PackageName     string
	APIImportPath   string
	APIAlias        string
	Imports         []string
	Types           []typeInfo
	Requests        []methodInfo
	Events          []methodInfo
	HasRequests     bool
	HasEvents       bool
	HasCustomTypes  bool
	Implementation  string
	RequestConstMax int
}

const clientTemplate = `// Code generated by {{ .Generator }}; DO NOT EDIT.

package {{ .PackageName }}

import (
	"fmt"
	"time"

	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
{{- range .Imports }}
	"{{ . }}"
{{- end }}
)

const (
	ServiceName = "{{ .ServiceName }}"
	ServiceID   uint32 = {{ .ServiceID }}
)

{{- if .HasRequests }}

const (
{{- range .Requests }}
	{{ .RequestConst }} uint16 = 0x{{ printf "%04x" .RequestID }}
{{- end }}
)
{{- end }}

{{- if .HasEvents }}

const (
{{- range .Events }}
	{{ .EventConst }} uint16 = 0x{{ printf "%04x" .RequestID }}
{{- end }}
)
{{- end }}

{{- if .HasCustomTypes }}
{{- range .Types }}

type {{ .Name }} struct {
{{- range .Fields }}
	{{ .Name }} {{ .Type }}
{{- end }}
}

func (v {{ .Name }}) encodeTo(enc *sutra.Encoder) {
{{- range .Fields }}
{{- if .IsSlice }}
	enc.PutUint32(uint32(len(v.{{ .Name }})))
	for i := range v.{{ .Name }} {
		v.{{ .Name }}[i].encodeTo(enc)
	}
{{- else if ne .EncCast "" }}
	enc.{{ .EncMethod }}({{ .EncCast }}(v.{{ .Name }}))
{{- else }}
	enc.{{ .EncMethod }}(v.{{ .Name }})
{{- end }}
{{- end }}
}

func (v *{{ .Name }}) decodeFrom(dec *sutra.Decoder) {
{{- range .Fields }}
{{- if .IsSlice }}
	{
		n := int(dec.Uint32())
		v.{{ .Name }} = make([]{{ .SliceElem }}, n)
		for i := range v.{{ .Name }} {
			v.{{ .Name }}[i].decodeFrom(dec)
		}
	}
{{- else if ne .DecCast "" }}
	v.{{ .Name }} = {{ .DecCast }}(dec.{{ .DecMethod }}())
{{- else }}
	v.{{ .Name }} = dec.{{ .DecMethod }}()
{{- end }}
{{- end }}
}

func (v {{ .Name }}) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *{{ .Name }}) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}
{{- end }}
{{- end }}

type Client struct {
	client  *sutra.Client
	timeout time.Duration
}

func NewClient(socketPath string) (*Client, error) {
	if socketPath == "" {
		socketPath = fs.Resolve("service:" + ServiceName)
	}
	c, err := sutra.Connect(socketPath)
	if err != nil {
		return nil, err
	}
	return &Client{
		client:  c,
		timeout: 5 * time.Second,
	}, nil
}

func (c *Client) Close() error {
	return c.client.Close()
}

func (c *Client) SetTimeout(timeout time.Duration) {
	c.timeout = timeout
}

{{- range .Requests }}

func (c *Client) {{ .Name }}(req {{ .RequestType }}){{ if .OneWay }} error{{ else }} ({{ .ResponseType }}, error){{ end }} {
	payload, err := encodePayload(req)
	if err != nil {
		{{- if .OneWay }}
		return err
		{{- else }}
		var zero {{ .ResponseType }}
		return zero, err
		{{- end }}
	}
	{{- if .OneWay }}
	return c.client.Send(sutra.IDService, {{ .RequestConst }}, payload)
	{{- else }}
	resp, err := c.client.Call(sutra.IDService, {{ .RequestConst }}, payload, c.timeout)
	if err != nil {
		var zero {{ .ResponseType }}
		return zero, err
	}
	var out {{ .ResponseType }}
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero {{ .ResponseType }}
		return zero, err
	}
	return out, nil
	{{- end }}
}
{{- end }}

{{- range .Events }}

func (c *Client) On{{ .Name }}(fn func(sender uint32, ev {{ .RequestType }})) {
	c.client.On({{ .EventConst }}, func(t *sutra.Transaction) {
		var value {{ .RequestType }}
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}
{{- end }}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
`

const serviceTemplate = `// Code generated by {{ .Generator }}; DO NOT EDIT.

package main

import (
	"fmt"

	{{ .APIAlias }} "{{ .APIImportPath }}"
	"avyos.dev/pkg/sutra"
)

type APIHandler interface {
{{- range .Requests }}
	{{ .Name }}(sender uint32, req {{ .ServerRequestType }}){{ if .OneWay }} error{{ else }} ({{ .ServerResponseType }}, error){{ end }}
{{- end }}
}

func RegisterHandlers(service *sutra.Service, handler APIHandler) {
{{- range .Requests }}
	service.Handle({{ $.APIAlias }}.{{ .RequestConst }}, func(t *sutra.Transaction) ([]byte, error) {
		var req {{ .ServerRequestType }}
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		{{- if .OneWay }}
		if err := handler.{{ .Name }}(t.Sender, req); err != nil {
			return nil, err
		}
		return nil, nil
		{{- else }}
		resp, err := handler.{{ .Name }}(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
		{{- end }}
	})
{{- end }}
}

{{- range .Events }}

func Emit{{ .Name }}(service *sutra.Service, destination uint32, ev {{ .ServerRequestType }}) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, {{ $.APIAlias }}.{{ .EventConst }}, payload)
}
{{- end }}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
`

const implTemplate = `// Code generated by {{ .Generator }}. You can edit this file.

package main

import (
	"fmt"

	{{ .APIAlias }} "{{ .APIImportPath }}"
)

type Handler struct{}

{{- range .Requests }}
func (h *Handler) {{ .Name }}(sender uint32, req {{ .ServerRequestType }}){{ if .OneWay }} error{{ else }} ({{ .ServerResponseType }}, error){{ end }} {
	_ = sender
	_ = req
	{{- if .OneWay }}
	return fmt.Errorf("{{ .Name }} not implemented")
	{{- else }}
	var out {{ .ServerResponseType }}
	return out, fmt.Errorf("{{ .Name }} not implemented")
	{{- end }}
}

{{- end }}
`

func main() {
	apiRoot := flag.String("api-root", "api", "API specs root directory (expects <root>/<service>/api.json)")
	service := flag.String("service", "", "Service name directory under api root")
	all := flag.Bool("all", false, "Generate all services in api root")
	clientOutName := flag.String("client-out", "zz_generated.go", "Output filename for generated client API in api/<service>")
	serviceOutName := flag.String("service-out", "zz_generated.go", "Output filename for generated service API in services/<service>")
	flag.Parse()

	apiRootPath, err := filepath.Abs(*apiRoot)
	if err != nil {
		fail("resolve api root %q: %v", *apiRoot, err)
	}
	projectRoot := filepath.Dir(apiRootPath)

	modulePath, err := moduleName()
	if err != nil {
		fail("failed to read module path: %v", err)
	}

	targets, err := discoverServices(apiRootPath, *service, *all)
	if err != nil {
		fail("%v", err)
	}
	if len(targets) == 0 {
		fail("no api specs found in %q", *apiRoot)
	}

	for _, serviceDir := range targets {
		specPath := filepath.Join(apiRootPath, serviceDir, "api.json")
		spec, err := readSpec(specPath)
		if err != nil {
			fail("%s: %v", specPath, err)
		}

		if err := validateSpec(spec); err != nil {
			fail("%s: %v", specPath, err)
		}

		data := buildTemplateData(spec, serviceDir, modulePath)

		clientOut := filepath.Join(apiRootPath, serviceDir, *clientOutName)
		if err := generateFile(clientOut, clientTemplate, data); err != nil {
			fail("generate %s: %v", clientOut, err)
		}

		svcDir := filepath.Join(projectRoot, "services", serviceDir)
		if err := os.MkdirAll(svcDir, 0755); err != nil {
			fail("create %s: %v", svcDir, err)
		}

		serverOut := filepath.Join(svcDir, *serviceOutName)
		if err := generateFile(serverOut, serviceTemplate, data); err != nil {
			fail("generate %s: %v", serverOut, err)
		}

		implOut := filepath.Join(svcDir, "impl.go")
		if _, err := os.Stat(implOut); errors.Is(err, os.ErrNotExist) {
			if err := generateFile(implOut, implTemplate, data); err != nil {
				fail("generate %s: %v", implOut, err)
			}
		}

		fmt.Printf("generated %s: %s, %s\n", serviceDir, clientOut, serverOut)
	}
}

func discoverServices(apiRoot, service string, all bool) ([]string, error) {
	if service != "" {
		return []string{service}, nil
	}

	pattern := filepath.Join(apiRoot, "*", "api.json")
	files, err := filepath.Glob(pattern)
	if err != nil {
		return nil, err
	}

	out := make([]string, 0, len(files))
	for _, f := range files {
		out = append(out, filepath.Base(filepath.Dir(f)))
	}
	sort.Strings(out)
	if len(out) == 0 && !all {
		return nil, fmt.Errorf("no service provided and no api.json found")
	}
	return out, nil
}

func readSpec(path string) (*apiSpec, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var spec apiSpec
	if err := json.Unmarshal(data, &spec); err != nil {
		return nil, err
	}
	return &spec, nil
}

func validateSpec(spec *apiSpec) error {
	if strings.TrimSpace(spec.Service.Name) == "" {
		return errors.New("service.name is required")
	}
	seen := make(map[uint16]string)
	checkID := func(id uint16, kind, name string) error {
		if prev, ok := seen[id]; ok {
			return fmt.Errorf("duplicate id 0x%04x for %s %q (already used by %s)", id, kind, name, prev)
		}
		seen[id] = fmt.Sprintf("%s %q", kind, name)
		return nil
	}

	for _, r := range spec.Requests {
		if strings.TrimSpace(r.Name) == "" {
			return errors.New("request.name is required")
		}
		if err := checkID(uint16(r.ID), "request", r.Name); err != nil {
			return err
		}
	}
	for _, e := range spec.Events {
		if strings.TrimSpace(e.Name) == "" {
			return errors.New("event.name is required")
		}
		if err := checkID(uint16(e.ID), "event", e.Name); err != nil {
			return err
		}
	}
	return nil
}

// binaryTypeMapping holds encoder/decoder metadata for a single Go type.
type binaryTypeMapping struct {
	EncMethod string
	DecMethod string
	EncCast   string
	DecCast   string
	IsSlice   bool
	SliceElem string
}

// resolveBinaryType maps a Go type to its binary encoder/decoder methods.
func resolveBinaryType(goType string) binaryTypeMapping {
	// []byte is a single blob, not a repeated byte.
	if goType == "[]byte" {
		return binaryTypeMapping{EncMethod: "PutBytes", DecMethod: "Bytes"}
	}
	if strings.HasPrefix(goType, "[]") {
		return binaryTypeMapping{IsSlice: true, SliceElem: goType[2:]}
	}
	switch goType {
	case "uint8", "byte":
		return binaryTypeMapping{EncMethod: "PutUint8", DecMethod: "Uint8"}
	case "uint16":
		return binaryTypeMapping{EncMethod: "PutUint16", DecMethod: "Uint16"}
	case "uint32":
		return binaryTypeMapping{EncMethod: "PutUint32", DecMethod: "Uint32"}
	case "uint64":
		return binaryTypeMapping{EncMethod: "PutUint64", DecMethod: "Uint64"}
	case "int":
		return binaryTypeMapping{EncMethod: "PutInt", DecMethod: "Int"}
	case "int32":
		return binaryTypeMapping{EncMethod: "PutInt32", DecMethod: "Int32"}
	case "bool":
		return binaryTypeMapping{EncMethod: "PutBool", DecMethod: "Bool"}
	case "string":
		return binaryTypeMapping{EncMethod: "PutString", DecMethod: "String"}
	case "rune":
		return binaryTypeMapping{EncMethod: "PutRune", DecMethod: "Rune"}
	case "graphics.Key":
		return binaryTypeMapping{EncMethod: "PutInt", DecMethod: "Int", EncCast: "int", DecCast: "graphics.Key"}
	default:
		return binaryTypeMapping{}
	}
}

func buildTemplateData(spec *apiSpec, serviceDir, modulePath string) templateData {
	pkg := spec.Service.Package
	if pkg == "" {
		pkg = sanitizePackage(serviceDir)
	}

	apiAlias := sanitizePackage(serviceDir) + "api"

	reqs := make([]methodInfo, 0, len(spec.Requests))
	for _, r := range spec.Requests {
		reqType := normalizeType(firstNonEmpty(r.RequestType, r.PayloadType, "[]byte"))
		respType := normalizeType(firstNonEmpty(r.ResponseType, "[]byte"))
		reqs = append(reqs, methodInfo{
			Name:               exportName(r.Name),
			RequestID:          uint16(r.ID),
			RequestConst:       "Request" + exportName(r.Name),
			EventConst:         "Event" + exportName(r.Name),
			RequestType:        reqType,
			ResponseType:       respType,
			ServerRequestType:  qualifyTypeForService(reqType, apiAlias),
			ServerResponseType: qualifyTypeForService(respType, apiAlias),
			OneWay:             r.OneWay,
			Comment:            r.Comment,
		})
	}

	evs := make([]methodInfo, 0, len(spec.Events))
	for _, e := range spec.Events {
		evType := normalizeType(firstNonEmpty(e.RequestType, e.PayloadType, "[]byte"))
		evs = append(evs, methodInfo{
			Name:              exportName(e.Name),
			RequestID:         uint16(e.ID),
			RequestConst:      "Request" + exportName(e.Name),
			EventConst:        "Event" + exportName(e.Name),
			RequestType:       evType,
			ResponseType:      normalizeType(firstNonEmpty(e.ResponseType, "[]byte")),
			ServerRequestType: qualifyTypeForService(evType, apiAlias),
			OneWay:            true,
			Comment:           e.Comment,
		})
	}

	types := make([]typeInfo, 0, len(spec.Types))
	for _, t := range spec.Types {
		ti := typeInfo{Name: exportName(t.Name)}
		for _, f := range t.Fields {
			goType := normalizeType(f.Type)
			bi := resolveBinaryType(goType)
			ti.Fields = append(ti.Fields, fieldInfo{
				Name:      exportName(f.Name),
				Type:      goType,
				EncMethod: bi.EncMethod,
				DecMethod: bi.DecMethod,
				EncCast:   bi.EncCast,
				DecCast:   bi.DecCast,
				IsSlice:   bi.IsSlice,
				SliceElem: bi.SliceElem,
			})
		}
		types = append(types, ti)
	}

	imports := append([]string(nil), spec.Imports...)
	sort.Strings(imports)

	return templateData{
		Generator:      "tools/apigen",
		ServiceDir:     serviceDir,
		ServiceName:    spec.Service.Name,
		ServiceID:      uint32(spec.Service.ID),
		PackageName:    pkg,
		APIImportPath:  filepath.ToSlash(filepath.Join(modulePath, "api", serviceDir)),
		APIAlias:       apiAlias,
		Imports:        imports,
		Types:          types,
		Requests:       reqs,
		Events:         evs,
		HasRequests:    len(reqs) > 0,
		HasEvents:      len(evs) > 0,
		HasCustomTypes: len(types) > 0,
	}
}

func qualifyTypeForService(t, alias string) string {
	t = strings.TrimSpace(t)
	if t == "" {
		return "[]byte"
	}
	if strings.HasPrefix(t, "[]") {
		return "[]" + qualifyTypeForService(t[2:], alias)
	}
	if strings.HasPrefix(t, "*") {
		return "*" + qualifyTypeForService(t[1:], alias)
	}
	if strings.Contains(t, ".") || strings.Contains(t, "{") || strings.HasPrefix(t, "map[") {
		return t
	}
	if isBuiltinType(t) {
		return t
	}
	return alias + "." + t
}

func isBuiltinType(t string) bool {
	switch t {
	case "string", "bool",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"byte", "rune",
		"float32", "float64",
		"any", "interface{}":
		return true
	default:
		return false
	}
}

func generateFile(path, tmpl string, data templateData) error {
	t, err := template.New("gen").Funcs(template.FuncMap{
		"lowerFirst": lowerFirst,
	}).Parse(tmpl)
	if err != nil {
		return err
	}

	var b bytes.Buffer
	if err := t.Execute(&b, data); err != nil {
		return err
	}

	src := b.Bytes()
	if strings.HasSuffix(path, ".go") {
		fmtSrc, err := format.Source(src)
		if err != nil {
			return fmt.Errorf("gofmt %s: %w\n%s", path, err, src)
		}
		src = fmtSrc
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, src, 0644)
}

func moduleName() (string, error) {
	goModPath, err := findGoMod(".")
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(goModPath)
	if err != nil {
		return "", err
	}
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	return "", errors.New("module directive not found in go.mod")
}

func findGoMod(start string) (string, error) {
	dir, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}

	for {
		candidate := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("go.mod not found")
		}
		dir = parent
	}
}

func exportName(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "Unnamed"
	}
	parts := splitIdentifier(s)
	for i := range parts {
		parts[i] = strings.Title(parts[i]) //nolint:staticcheck
	}
	out := strings.Join(parts, "")
	if out == "" {
		return "Unnamed"
	}
	return out
}

func sanitizePackage(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	if s == "" {
		return "api"
	}
	parts := splitIdentifier(s)
	return strings.Join(parts, "")
}

func splitIdentifier(s string) []string {
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	s = strings.ReplaceAll(s, " ", "_")
	raw := strings.Split(s, "_")
	out := make([]string, 0, len(raw))
	for _, p := range raw {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	if len(out) == 0 {
		return []string{"api"}
	}
	return out
}

func normalizeType(t string) string {
	t = strings.TrimSpace(t)
	if t == "" {
		return "[]byte"
	}
	return t
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
