// Code generated by tools/apigen; DO NOT EDIT.

package distro

import (
	"fmt"
	"time"

	"avyos.dev/pkg/fs"
	"avyos.dev/pkg/sutra"
)

const (
	ServiceName        = "dev.avyos.distro"
	ServiceID   uint32 = 112
)

const (
	RequestStatus      uint16 = 0x0201
	RequestInstall     uint16 = 0x0202
	RequestRun         uint16 = 0x0203
	RequestRemove      uint16 = 0x0204
	RequestShellOpen   uint16 = 0x0205
	RequestShellInput  uint16 = 0x0206
	RequestShellResize uint16 = 0x0207
	RequestShellClose  uint16 = 0x0208
)

const (
	EventShellOutput uint16 = 0x0301
	EventShellExit   uint16 = 0x0302
)

type Empty struct {
}

func (v Empty) encodeTo(enc *sutra.Encoder) {
}

func (v *Empty) decodeFrom(dec *sutra.Decoder) {
}

func (v Empty) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *Empty) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type StatusResponse struct {
	Installed bool
	Path      string
	Size      int
}

func (v StatusResponse) encodeTo(enc *sutra.Encoder) {
	enc.PutBool(v.Installed)
	enc.PutString(v.Path)
	enc.PutInt(v.Size)
}

func (v *StatusResponse) decodeFrom(dec *sutra.Decoder) {
	v.Installed = dec.Bool()
	v.Path = dec.String()
	v.Size = dec.Int()
}

func (v StatusResponse) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *StatusResponse) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type InstallRequest struct {
	URL string
}

func (v InstallRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.URL)
}

func (v *InstallRequest) decodeFrom(dec *sutra.Decoder) {
	v.URL = dec.String()
}

func (v InstallRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *InstallRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type RunRequest struct {
	Command string
	Workdir string
	Bind    string
	Env     string
	Input   []byte
}

func (v RunRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Command)
	enc.PutString(v.Workdir)
	enc.PutString(v.Bind)
	enc.PutString(v.Env)
	enc.PutBytes(v.Input)
}

func (v *RunRequest) decodeFrom(dec *sutra.Decoder) {
	v.Command = dec.String()
	v.Workdir = dec.String()
	v.Bind = dec.String()
	v.Env = dec.String()
	v.Input = dec.Bytes()
}

func (v RunRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *RunRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type RunResult struct {
	Stdout   []byte
	Stderr   []byte
	ExitCode int
}

func (v RunResult) encodeTo(enc *sutra.Encoder) {
	enc.PutBytes(v.Stdout)
	enc.PutBytes(v.Stderr)
	enc.PutInt(v.ExitCode)
}

func (v *RunResult) decodeFrom(dec *sutra.Decoder) {
	v.Stdout = dec.Bytes()
	v.Stderr = dec.Bytes()
	v.ExitCode = dec.Int()
}

func (v RunResult) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *RunResult) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ShellOpenRequest struct {
	Workdir string
	Bind    string
	Env     string
	Rows    int
	Cols    int
}

func (v ShellOpenRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutString(v.Workdir)
	enc.PutString(v.Bind)
	enc.PutString(v.Env)
	enc.PutInt(v.Rows)
	enc.PutInt(v.Cols)
}

func (v *ShellOpenRequest) decodeFrom(dec *sutra.Decoder) {
	v.Workdir = dec.String()
	v.Bind = dec.String()
	v.Env = dec.String()
	v.Rows = dec.Int()
	v.Cols = dec.Int()
}

func (v ShellOpenRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ShellOpenRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ShellSession struct {
	SessionID uint32
}

func (v ShellSession) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.SessionID)
}

func (v *ShellSession) decodeFrom(dec *sutra.Decoder) {
	v.SessionID = dec.Uint32()
}

func (v ShellSession) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ShellSession) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ShellInputRequest struct {
	SessionID uint32
	Data      []byte
}

func (v ShellInputRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.SessionID)
	enc.PutBytes(v.Data)
}

func (v *ShellInputRequest) decodeFrom(dec *sutra.Decoder) {
	v.SessionID = dec.Uint32()
	v.Data = dec.Bytes()
}

func (v ShellInputRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ShellInputRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ShellResizeRequest struct {
	SessionID uint32
	Rows      int
	Cols      int
}

func (v ShellResizeRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.SessionID)
	enc.PutInt(v.Rows)
	enc.PutInt(v.Cols)
}

func (v *ShellResizeRequest) decodeFrom(dec *sutra.Decoder) {
	v.SessionID = dec.Uint32()
	v.Rows = dec.Int()
	v.Cols = dec.Int()
}

func (v ShellResizeRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ShellResizeRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ShellCloseRequest struct {
	SessionID uint32
}

func (v ShellCloseRequest) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.SessionID)
}

func (v *ShellCloseRequest) decodeFrom(dec *sutra.Decoder) {
	v.SessionID = dec.Uint32()
}

func (v ShellCloseRequest) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ShellCloseRequest) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ShellOutputEvent struct {
	SessionID uint32
	Data      []byte
}

func (v ShellOutputEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.SessionID)
	enc.PutBytes(v.Data)
}

func (v *ShellOutputEvent) decodeFrom(dec *sutra.Decoder) {
	v.SessionID = dec.Uint32()
	v.Data = dec.Bytes()
}

func (v ShellOutputEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ShellOutputEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type ShellExitEvent struct {
	SessionID uint32
	ExitCode  int
}

func (v ShellExitEvent) encodeTo(enc *sutra.Encoder) {
	enc.PutUint32(v.SessionID)
	enc.PutInt(v.ExitCode)
}

func (v *ShellExitEvent) decodeFrom(dec *sutra.Decoder) {
	v.SessionID = dec.Uint32()
	v.ExitCode = dec.Int()
}

func (v ShellExitEvent) MarshalBinary() []byte {
	enc := sutra.NewEncoder(64)
	v.encodeTo(enc)
	return enc.Bytes()
}

func (v *ShellExitEvent) UnmarshalBinary(data []byte) error {
	dec := sutra.NewDecoder(data)
	v.decodeFrom(dec)
	return dec.Err()
}

type Client struct {
	client  *sutra.Client
	timeout time.Duration
}

func NewClient(socketPath string) (*Client, error) {
	if socketPath == "" {
		socketPath = fs.Resolve("system:%s", ServiceName)
	}
	c, err := sutra.Connect(socketPath)
	if err != nil {
		return nil, err
	}
	return &Client{
		client:  c,
		timeout: 5 * time.Second,
	}, nil
}

func (c *Client) Close() error {
	return c.client.Close()
}

func (c *Client) SetTimeout(timeout time.Duration) {
	c.timeout = timeout
}

func (c *Client) Status(req Empty) (StatusResponse, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero StatusResponse
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestStatus, payload, c.timeout)
	if err != nil {
		var zero StatusResponse
		return zero, err
	}
	var out StatusResponse
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero StatusResponse
		return zero, err
	}
	return out, nil
}

func (c *Client) Install(req InstallRequest) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestInstall, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) Run(req RunRequest) (RunResult, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero RunResult
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestRun, payload, c.timeout)
	if err != nil {
		var zero RunResult
		return zero, err
	}
	var out RunResult
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero RunResult
		return zero, err
	}
	return out, nil
}

func (c *Client) Remove(req Empty) (Empty, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero Empty
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestRemove, payload, c.timeout)
	if err != nil {
		var zero Empty
		return zero, err
	}
	var out Empty
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero Empty
		return zero, err
	}
	return out, nil
}

func (c *Client) ShellOpen(req ShellOpenRequest) (ShellSession, error) {
	payload, err := encodePayload(req)
	if err != nil {
		var zero ShellSession
		return zero, err
	}
	resp, err := c.client.Call(sutra.IDService, RequestShellOpen, payload, c.timeout)
	if err != nil {
		var zero ShellSession
		return zero, err
	}
	var out ShellSession
	if err := decodePayload(resp.Payload, &out); err != nil {
		var zero ShellSession
		return zero, err
	}
	return out, nil
}

func (c *Client) ShellInput(req ShellInputRequest) error {
	payload, err := encodePayload(req)
	if err != nil {
		return err
	}
	return c.client.Send(sutra.IDService, RequestShellInput, payload)
}

func (c *Client) ShellResize(req ShellResizeRequest) error {
	payload, err := encodePayload(req)
	if err != nil {
		return err
	}
	return c.client.Send(sutra.IDService, RequestShellResize, payload)
}

func (c *Client) ShellClose(req ShellCloseRequest) error {
	payload, err := encodePayload(req)
	if err != nil {
		return err
	}
	return c.client.Send(sutra.IDService, RequestShellClose, payload)
}

func (c *Client) OnShellOutput(fn func(sender uint32, ev ShellOutputEvent)) {
	c.client.On(EventShellOutput, func(t *sutra.Transaction) {
		var value ShellOutputEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

func (c *Client) OnShellExit(fn func(sender uint32, ev ShellExitEvent)) {
	c.client.On(EventShellExit, func(t *sutra.Transaction) {
		var value ShellExitEvent
		if err := decodePayload(t.Payload, &value); err != nil {
			return
		}
		fn(t.Sender, value)
	})
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
