// Code generated by tools/apigen; DO NOT EDIT.

package main

import (
	"fmt"

	distroapi "avyos.dev/api/distro"
	"avyos.dev/pkg/sutra"
)

type APIHandler interface {
	Status(sender uint32, req distroapi.Empty) (distroapi.StatusResponse, error)
	Install(sender uint32, req distroapi.InstallRequest) (distroapi.Empty, error)
	Run(sender uint32, req distroapi.RunRequest) (distroapi.RunResult, error)
	Remove(sender uint32, req distroapi.Empty) (distroapi.Empty, error)
	ShellOpen(sender uint32, req distroapi.ShellOpenRequest) (distroapi.ShellSession, error)
	ShellInput(sender uint32, req distroapi.ShellInputRequest) error
	ShellResize(sender uint32, req distroapi.ShellResizeRequest) error
	ShellClose(sender uint32, req distroapi.ShellCloseRequest) error
}

func RegisterHandlers(service *sutra.Service, handler APIHandler) {
	service.Handle(distroapi.RequestStatus, func(t *sutra.Transaction) ([]byte, error) {
		var req distroapi.Empty
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Status(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(distroapi.RequestInstall, func(t *sutra.Transaction) ([]byte, error) {
		var req distroapi.InstallRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Install(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(distroapi.RequestRun, func(t *sutra.Transaction) ([]byte, error) {
		var req distroapi.RunRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Run(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(distroapi.RequestRemove, func(t *sutra.Transaction) ([]byte, error) {
		var req distroapi.Empty
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Remove(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(distroapi.RequestShellOpen, func(t *sutra.Transaction) ([]byte, error) {
		var req distroapi.ShellOpenRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.ShellOpen(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(distroapi.RequestShellInput, func(t *sutra.Transaction) ([]byte, error) {
		var req distroapi.ShellInputRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		if err := handler.ShellInput(t.Sender, req); err != nil {
			return nil, err
		}
		return nil, nil
	})
	service.Handle(distroapi.RequestShellResize, func(t *sutra.Transaction) ([]byte, error) {
		var req distroapi.ShellResizeRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		if err := handler.ShellResize(t.Sender, req); err != nil {
			return nil, err
		}
		return nil, nil
	})
	service.Handle(distroapi.RequestShellClose, func(t *sutra.Transaction) ([]byte, error) {
		var req distroapi.ShellCloseRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		if err := handler.ShellClose(t.Sender, req); err != nil {
			return nil, err
		}
		return nil, nil
	})
}

func EmitShellOutput(service *sutra.Service, destination uint32, ev distroapi.ShellOutputEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, distroapi.EventShellOutput, payload)
}

func EmitShellExit(service *sutra.Service, destination uint32, ev distroapi.ShellExitEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, distroapi.EventShellExit, payload)
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
