// Code generated by tools/apigen. You can edit this file.

package main

import (
	"fmt"

	displayapi "avyos.dev/api/display"
)

type Handler struct{}

func (h *Handler) CreateWindow(sender uint32, req displayapi.CreateWindowRequest) (displayapi.WindowCreatedEvent, error) {
	_ = sender
	_ = req
	var out displayapi.WindowCreatedEvent
	return out, fmt.Errorf("CreateWindow not implemented")
}
func (h *Handler) DestroyWindow(sender uint32, req displayapi.DestroyWindowRequest) (displayapi.Empty, error) {
	_ = sender
	_ = req
	var out displayapi.Empty
	return out, fmt.Errorf("DestroyWindow not implemented")
}
func (h *Handler) SetTitle(sender uint32, req displayapi.SetTitleRequest) (displayapi.Empty, error) {
	_ = sender
	_ = req
	var out displayapi.Empty
	return out, fmt.Errorf("SetTitle not implemented")
}
func (h *Handler) Damage(sender uint32, req displayapi.DamageRequest) (displayapi.Empty, error) {
	_ = sender
	_ = req
	var out displayapi.Empty
	return out, fmt.Errorf("Damage not implemented")
}
func (h *Handler) Resize(sender uint32, req displayapi.ResizeRequest) (displayapi.Empty, error) {
	_ = sender
	_ = req
	var out displayapi.Empty
	return out, fmt.Errorf("Resize not implemented")
}
func (h *Handler) Move(sender uint32, req displayapi.MoveRequest) (displayapi.Empty, error) {
	_ = sender
	_ = req
	var out displayapi.Empty
	return out, fmt.Errorf("Move not implemented")
}
func (h *Handler) CreateLayer(sender uint32, req displayapi.CreateLayerRequest) (displayapi.WindowCreatedEvent, error) {
	_ = sender
	_ = req
	var out displayapi.WindowCreatedEvent
	return out, fmt.Errorf("CreateLayer not implemented")
}
func (h *Handler) CreatePopup(sender uint32, req displayapi.CreatePopupRequest) (displayapi.WindowCreatedEvent, error) {
	_ = sender
	_ = req
	var out displayapi.WindowCreatedEvent
	return out, fmt.Errorf("CreatePopup not implemented")
}
func (h *Handler) ListWindows(sender uint32, req displayapi.Empty) (displayapi.WindowListEvent, error) {
	_ = sender
	_ = req
	var out displayapi.WindowListEvent
	return out, fmt.Errorf("ListWindows not implemented")
}
func (h *Handler) SetWindowState(sender uint32, req displayapi.SetWindowStateRequest) (displayapi.Empty, error) {
	_ = sender
	_ = req
	var out displayapi.Empty
	return out, fmt.Errorf("SetWindowState not implemented")
}
func (h *Handler) RegisterSession(sender uint32, req displayapi.RegisterSessionRequest) (displayapi.Empty, error) {
	_ = sender
	_ = req
	var out displayapi.Empty
	return out, fmt.Errorf("RegisterSession not implemented")
}
func (h *Handler) SetActiveSession(sender uint32, req displayapi.SetActiveSessionRequest) (displayapi.Empty, error) {
	_ = sender
	_ = req
	var out displayapi.Empty
	return out, fmt.Errorf("SetActiveSession not implemented")
}
func (h *Handler) GetActiveSession(sender uint32, req displayapi.Empty) (displayapi.ActiveSessionEvent, error) {
	_ = sender
	_ = req
	var out displayapi.ActiveSessionEvent
	return out, fmt.Errorf("GetActiveSession not implemented")
}
func (h *Handler) RegisterShortcut(sender uint32, req displayapi.RegisterShortcutRequest) (displayapi.Empty, error) {
	_ = sender
	_ = req
	var out displayapi.Empty
	return out, fmt.Errorf("RegisterShortcut not implemented")
}
func (h *Handler) UnregisterShortcut(sender uint32, req displayapi.UnregisterShortcutRequest) (displayapi.Empty, error) {
	_ = sender
	_ = req
	var out displayapi.Empty
	return out, fmt.Errorf("UnregisterShortcut not implemented")
}
