// Code generated by tools/apigen; DO NOT EDIT.

package main

import (
	"fmt"

	displayapi "avyos.dev/api/display"
	"avyos.dev/pkg/sutra"
)

type APIHandler interface {
	CreateWindow(sender uint32, req displayapi.CreateWindowRequest) (displayapi.WindowCreatedEvent, error)
	DestroyWindow(sender uint32, req displayapi.DestroyWindowRequest) (displayapi.Empty, error)
	SetTitle(sender uint32, req displayapi.SetTitleRequest) (displayapi.Empty, error)
	Damage(sender uint32, req displayapi.DamageRequest) (displayapi.Empty, error)
	Resize(sender uint32, req displayapi.ResizeRequest) (displayapi.Empty, error)
	Move(sender uint32, req displayapi.MoveRequest) (displayapi.Empty, error)
	CreateLayer(sender uint32, req displayapi.CreateLayerRequest) (displayapi.WindowCreatedEvent, error)
	CreatePopup(sender uint32, req displayapi.CreatePopupRequest) (displayapi.WindowCreatedEvent, error)
	ListWindows(sender uint32, req displayapi.Empty) (displayapi.WindowListEvent, error)
	SetWindowState(sender uint32, req displayapi.SetWindowStateRequest) (displayapi.Empty, error)
	RegisterSession(sender uint32, req displayapi.RegisterSessionRequest) (displayapi.Empty, error)
	SetActiveSession(sender uint32, req displayapi.SetActiveSessionRequest) (displayapi.Empty, error)
	GetActiveSession(sender uint32, req displayapi.Empty) (displayapi.ActiveSessionEvent, error)
	RegisterShortcut(sender uint32, req displayapi.RegisterShortcutRequest) (displayapi.Empty, error)
	UnregisterShortcut(sender uint32, req displayapi.UnregisterShortcutRequest) (displayapi.Empty, error)
}

func RegisterHandlers(service *sutra.Service, handler APIHandler) {
	service.Handle(displayapi.RequestCreateWindow, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.CreateWindowRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.CreateWindow(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestDestroyWindow, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.DestroyWindowRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.DestroyWindow(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestSetTitle, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.SetTitleRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.SetTitle(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestDamage, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.DamageRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Damage(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestResize, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.ResizeRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Resize(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestMove, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.MoveRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.Move(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestCreateLayer, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.CreateLayerRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.CreateLayer(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestCreatePopup, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.CreatePopupRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.CreatePopup(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestListWindows, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.Empty
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.ListWindows(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestSetWindowState, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.SetWindowStateRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.SetWindowState(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestRegisterSession, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.RegisterSessionRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.RegisterSession(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestSetActiveSession, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.SetActiveSessionRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.SetActiveSession(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestGetActiveSession, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.Empty
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.GetActiveSession(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestRegisterShortcut, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.RegisterShortcutRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.RegisterShortcut(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
	service.Handle(displayapi.RequestUnregisterShortcut, func(t *sutra.Transaction) ([]byte, error) {
		var req displayapi.UnregisterShortcutRequest
		if err := decodePayload(t.Payload, &req); err != nil {
			return nil, err
		}
		resp, err := handler.UnregisterShortcut(t.Sender, req)
		if err != nil {
			return nil, err
		}
		return encodePayload(resp)
	})
}

func EmitWindowCreated(service *sutra.Service, destination uint32, ev displayapi.WindowCreatedEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventWindowCreated, payload)
}

func EmitConfigure(service *sutra.Service, destination uint32, ev displayapi.ConfigureEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventConfigure, payload)
}

func EmitClose(service *sutra.Service, destination uint32, ev displayapi.CloseEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventClose, payload)
}

func EmitPointerEnter(service *sutra.Service, destination uint32, ev displayapi.PointerEnterEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventPointerEnter, payload)
}

func EmitPointerLeave(service *sutra.Service, destination uint32, ev displayapi.PointerLeaveEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventPointerLeave, payload)
}

func EmitPointerMotion(service *sutra.Service, destination uint32, ev displayapi.PointerMotionEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventPointerMotion, payload)
}

func EmitPointerButton(service *sutra.Service, destination uint32, ev displayapi.PointerButtonEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventPointerButton, payload)
}

func EmitKey(service *sutra.Service, destination uint32, ev displayapi.KeyEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventKey, payload)
}

func EmitFocus(service *sutra.Service, destination uint32, ev displayapi.FocusEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventFocus, payload)
}

func EmitMoved(service *sutra.Service, destination uint32, ev displayapi.MovedEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventMoved, payload)
}

func EmitWindowList(service *sutra.Service, destination uint32, ev displayapi.WindowListEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventWindowList, payload)
}

func EmitSessionActivated(service *sutra.Service, destination uint32, ev displayapi.ActiveSessionEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventSessionActivated, payload)
}

func EmitSessionSuspended(service *sutra.Service, destination uint32, ev displayapi.ActiveSessionEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventSessionSuspended, payload)
}

func EmitSessionResumed(service *sutra.Service, destination uint32, ev displayapi.ActiveSessionEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventSessionResumed, payload)
}

func EmitShortcut(service *sutra.Service, destination uint32, ev displayapi.ShortcutEvent) error {
	payload, err := encodePayload(ev)
	if err != nil {
		return err
	}
	return service.Send(destination, displayapi.EventShortcut, payload)
}

type binaryEncoder interface {
	MarshalBinary() []byte
}

type binaryDecoder interface {
	UnmarshalBinary([]byte) error
}

func encodePayload(v any) ([]byte, error) {
	switch data := v.(type) {
	case []byte:
		return data, nil
	case binaryEncoder:
		return data.MarshalBinary(), nil
	default:
		return nil, fmt.Errorf("unsupported payload type %T", v)
	}
}

func decodePayload(data []byte, out any) error {
	switch ptr := out.(type) {
	case *[]byte:
		*ptr = append((*ptr)[:0], data...)
		return nil
	case binaryDecoder:
		return ptr.UnmarshalBinary(data)
	default:
		return fmt.Errorf("unsupported payload type %T", out)
	}
}
